version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: rakesh
      MYSQL_PASSWORD: Rakesh@1995
      MYSQL_DATABASE: sms
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    

  my-sms-app:
    container_name: spring-sms
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9001:8080
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/sms
      - spring.datasource.username=rakesh
      - spring.datasource.password=Rakesh@1995
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    restart: on-failure

